name: Build Redpanda on ARM 32-bit

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget git # nodejs npm sudo
          sudo npm install -g @bazel/bazelisk
          sudo ln -s -f /usr/local/bin/bazelisk /usr/local/bin/bazel

      - name: Install Redpanda System Dependencies
        run: sudo ./bazel/install-deps.sh

      - name: Build Redpanda
        run: bazel build --config=release redpanda

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: redpanda-artifacts
          path: bazel-bin